<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE xml [
<!ELEMENT xml (Thread*)>
<!ATTLIST xml 
version CDATA #REQUIRED
>
<!ELEMENT Thread (RelQuestion, RelComment*)>
<!ATTLIST Thread
 THREAD_SEQUENCE CDATA #REQUIRED
>
<!ELEMENT RelQuestion (RelQSubject, RelQBody)>
<!ATTLIST RelQuestion
RELQ_ID CDATA #REQUIRED
RELQ_CATEGORY CDATA #REQUIRED
RELQ_DATE CDATA #REQUIRED
RELQ_USERID CDATA #REQUIRED
RELQ_USERNAME CDATA #REQUIRED
>
<!ELEMENT RelQSubject (#PCDATA)>
<!ELEMENT RelQBody (#PCDATA)>
<!ELEMENT RelComment (RelCText)>
<!ATTLIST RelComment
RELC_ID CDATA #REQUIRED
RELC_DATE CDATA #REQUIRED
RELC_USERID CDATA #REQUIRED
RELC_USERNAME CDATA #REQUIRED
RELC_RELEVANCE2RELQ CDATA #REQUIRED
>
<!ELEMENT RelCText (#PCDATA)>
]>

<xml version="1.0">

	<Thread THREAD_SEQUENCE="Q1_R1">
		<RelQuestion RELQ_ID="Q1_R1" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2010-08-27 01:38:59" RELQ_USERID="U1" RELQ_USERNAME="sognabodl">
			<RelQSubject>massage oil</RelQSubject>
			<RelQBody>is there any place i can find scented massage oils in qatar?</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q1_R1_C1" RELC_DATE="2010-08-27 01:40:05" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Yes. It is right behind Kahrama in the National area.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C2" RELC_DATE="2010-08-27 01:42:59" RELC_USERID="U1" RELC_USERNAME="sognabodl" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>whats the name of the shop?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C3" RELC_DATE="2010-08-27 01:44:09" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Good">
			<RelCText>It's called Naseem Al-Nadir. Right next to the Smartlink shop. You'll find the chinese salesgirls at affordable prices there.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C4" RELC_DATE="2010-08-27 01:58:39" RELC_USERID="U1" RELC_USERNAME="sognabodl" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>dont want girls;want oil</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C5" RELC_DATE="2010-08-27 01:59:55" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Try Both ;) I'am just trying to be helpful. On a serious note - Please go there. you'll find what you are looking for.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C6" RELC_DATE="2010-08-27 02:02:53" RELC_USERID="U3" RELC_USERNAME="lawa" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>you mean oil and filter both</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C7" RELC_DATE="2010-08-27 02:04:29" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Yes Lawa...you couldn't be more right LOL</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C8" RELC_DATE="2010-08-27 02:08:19" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>What they offer?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C9" RELC_DATE="2010-08-27 02:08:39" RELC_USERID="U4" RELC_USERNAME="Swine Flu" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>FU did u try with that salesgirl ?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R1_C10" RELC_DATE="2010-08-27 02:10:33" RELC_USERID="U2" RELC_USERNAME="anonymous" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Swine - No I don't try with salesgirls. My taste is classy ;)</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q1_R6">
		<RelQuestion RELQ_ID="Q1_R6" RELQ_CATEGORY="Advice and Help" RELQ_DATE="2010-09-17 09:30:26" RELQ_USERID="U5" RELQ_USERNAME="ihthysham">
			<RelQSubject>Philipino Massage center</RelQSubject>
			<RelQBody>Hi;Can any one tell me a place where i can have a good massage drom philipinies????? yesterday i had a massage in Bio-Bil they charged me 300qr for 01 hour bt it is totally waste... pls advice me if theres any philipinos....</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q1_R6_C1" RELC_DATE="2010-09-17 09:58:22" RELC_USERID="U6" RELC_USERNAME="t_coffee_or_me" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Most massages in Qatar are a waste of money. All they do is just rub some oil. No body does deep tissue massage here.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C2" RELC_DATE="2010-09-17 10:09:59" RELC_USERID="U7" RELC_USERNAME="betty boop" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>my masseuse is very good. calling her from to time for home service. currently in the philippines for a month vacation; i guess. =( she is the best in aromatherapy massage.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C3" RELC_DATE="2010-09-17 10:45:46" RELC_USERID="U8" RELC_USERNAME="asif_khan" RELC_RELEVANCE2RELQ="Good">
			<RelCText>there is a massage center near mall roundabout in hilal opp. to woqood petrol station</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C4" RELC_DATE="2010-09-17 11:04:39" RELC_USERID="U9" RELC_USERNAME="Jhong_C" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Try Magic Touch in Abu Hamour (beside Abu Hamour Petrol Stn)it will just cost you 60QR per hour and I've seen a lot of Qataris as their customers.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C5" RELC_DATE="2010-09-17 11:11:55" RELC_USERID="U10" RELC_USERNAME="Alumnar" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Can anybody recommend a good place for head massages? I am constantly getting migranes and would like a head massage after the medication has done its job as I am left very drained. Thank you :)</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C6" RELC_DATE="2010-09-17 12:36:28" RELC_USERID="U11" RELC_USERNAME="roy_dig" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>call them they are good 44410410.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C7" RELC_DATE="2010-09-17 12:40:08" RELC_USERID="U10" RELC_USERNAME="Alumnar" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Hi Roy; what place is the contact number for that you posted?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C8" RELC_DATE="2010-09-17 12:44:02" RELC_USERID="U11" RELC_USERNAME="roy_dig" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I dont know the name; you can call them. Do it fast; they have sooooo many reservations ;)</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C9" RELC_DATE="2010-09-17 12:47:40" RELC_USERID="U10" RELC_USERNAME="Alumnar" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Roy; thanks; but is it a beauty salon or what? Do you at least know the location?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R6_C10" RELC_DATE="2010-09-27 16:25:30" RELC_USERID="U12" RELC_USERNAME="Spike80" RELC_RELEVANCE2RELQ="Good">
			<RelCText>"The BEST MASSAGE in Doha ""VALUE FOR MONEY"" from my opinion is @ Merzam Residence;(cream color building with light blue glass window); opposite of The Center (Mega Mart)Bin Mahmood. Price is very reasonable; QR 150 for one hour. Therapist is from Bali island and he was working at Ritz-Carlton Hotel in Dubai. Phone no: 44274037. www.merzamhotels.com"</RelCText>
		</RelComment>
	</Thread>
	<Thread THREAD_SEQUENCE="Q1_R8">
		<RelQuestion RELQ_ID="Q1_R8" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2008-04-27 12:29:54" RELQ_USERID="U13" RELQ_USERNAME="irrysa">
			<RelQSubject>Best place for massage</RelQSubject>
			<RelQBody>Tell me; where is the best place to go for a massage? Mind you; I don't want to spend 1000QR for it... (Guys; please don't come up with answers that you would gladly do it yourself; plz...) </RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q1_R8_C1" RELC_DATE="2008-04-27 12:32:47" RELC_USERID="U14" RELC_USERNAME="dragonfly212" RELC_RELEVANCE2RELQ="Good">
			<RelCText>"have you try lady siam massage next to toy ""r"" us al sadd? for one hour = 120riyal. not bad i must say Everybody is right Everybody is wrong; it depend where we stand."</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C2" RELC_DATE="2008-04-27 12:35:31" RELC_USERID="U15" RELC_USERNAME="Oryx" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I have never been for a massage! Can you believe it? Maybe I should go and try too! :)</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C3" RELC_DATE="2008-04-27 12:36:51" RELC_USERID="U16" RELC_USERNAME="catsniper" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Massage n ramada is not bad... If it's true that we are here to help others; then what exactly are the others here for?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C4" RELC_DATE="2008-04-27 12:37:39" RELC_USERID="U14" RELC_USERNAME="dragonfly212" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>never oryx?? well how about we make a date and book the place for us; what you say irrysa??? come on will be fun. when you want it let me know. i can even skip the work for this. hehehehe i love massage Everybody is right Everybody is wrong; it depend where we stand.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C5" RELC_DATE="2008-04-27 12:39:07" RELC_USERID="U14" RELC_USERNAME="dragonfly212" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>yeah... catsniper; i know that. i am member there too but they only have for gents not ladies Everybody is right Everybody is wrong; it depend where we stand.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C6" RELC_DATE="2008-04-27 12:40:15" RELC_USERID="U15" RELC_USERNAME="Oryx" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Yes... but guess what girlies I did a year course in the UK in holistic massage! But I have never been myself...so I would love too. Put me down for anti-stress! Can I have a cute boy in shorts  - oh sorry that wouldnt' de-stress me!</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C7" RELC_DATE="2008-04-27 12:41:17" RELC_USERID="U14" RELC_USERNAME="dragonfly212" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>lol oryx; sorry to say but they done by woman to woman only. and they not sexy bimbo either so i guess can be very relaxing. hehehehe Everybody is right Everybody is wrong; it depend where we stand.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C8" RELC_DATE="2008-04-27 12:44:35" RELC_USERID="U13" RELC_USERNAME="irrysa" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Mila; i'm IN! i used to be with a guy who was perfect in this...but i can't go to him now when i'm with someone else; now can i? If you're looking for a problem; you're probably gonna find one.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C9" RELC_DATE="2008-04-27 12:47:36" RELC_USERID="U17" RELC_USERNAME="Khanan" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>who is/was that lucky chap???</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R8_C10" RELC_DATE="2008-04-27 12:48:11" RELC_USERID="U14" RELC_USERNAME="dragonfly212" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>sure you can irrysa is only for massage. hehehehe wink strecth more your boundary. Everybody is right Everybody is wrong; it depend where we stand.</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q1_R10">
		<RelQuestion RELQ_ID="Q1_R10" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2006-11-08 11:33:10" RELQ_USERID="U18" RELQ_USERNAME="gringer">
			<RelQSubject>body massage</RelQSubject>
			<RelQBody>hi there; i can see a lot of massage center here; but i dont which one is better. can someone help me which massage center is good...and how much will it cost me? thanks</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q1_R10_C1" RELC_DATE="2006-11-08 12:34:04" RELC_USERID="U19" RELC_USERNAME="qatar127" RELC_RELEVANCE2RELQ="Good">
			<RelCText>So you are looking for a message !!! hmmmm i dont recommend any one of them; i went once and i was going to xxxxx with that semi guy; they all are shemales belive me; so if u r looking for that go ahead otherwise there is the only one who is the decent at al saad street; it is after al saad plaza if you are coming from the new traffic light near the BMW; it is called kotakel something like that. Good luck</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C2" RELC_DATE="2006-11-08 13:32:37" RELC_USERID="U20" RELC_USERNAME="porcupine" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Gringer; You can also try out the International Massage Centre on Al-Kinana Street. Separate entrances for men and women. They are from Kerala (India) and very good. I personally avail of the facility quite often. There is also a doctor at the Centre whom you can consult for any complaints. A one-hour full body massage is QRs. 100/-. Their telephone number is 4421343.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C3" RELC_DATE="2006-11-08 13:42:02" RELC_USERID="U21" RELC_USERNAME="Terramax" RELC_RELEVANCE2RELQ="Good">
			<RelCText>"There was a good Thai massage place next to the Thai ""restaurant"" in front of Doha Clinic; but I last time I was driving by it was closed. I wonder if anybody tried the Filipino Massage Centre on Najma (between C and D rings)."</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C4" RELC_DATE="2006-11-08 16:11:04" RELC_USERID="U22" RELC_USERNAME="Miss Canada" RELC_RELEVANCE2RELQ="Good">
			<RelCText>If you're female (both places only service women); I highly recommend: Bio-Bil Spa (across from the City Center) 493 4433 1 hour Traditional Aromatherapy Massage w/ oil – 150 QR Lady Siam Massage (next to Toys R Us) 435 4115 1 hour Traditional Thai Massage – 120 QR</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C5" RELC_DATE="2006-11-09 00:28:25" RELC_USERID="U23" RELC_USERNAME="cassie" RELC_RELEVANCE2RELQ="Good">
			<RelCText>ive seen a lot of MASSAGE PARLOR(all over d city i guess)..and tried d FILIPINO MASSAGE CENTER and terramax was right they were gud and d service was excellent..but m just curious though..haven't seen any facial center or facial spa here..or whatever u may call it.. have u?...</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C6" RELC_DATE="2006-11-09 12:34:14" RELC_USERID="U24" RELC_USERNAME="han19" RELC_RELEVANCE2RELQ="Good">
			<RelCText>good facial centres/spas;try marriott or ritz; they have a lovely spa; but expensive. a new place opened up opp city centre; its called bio something.they too specialise in the same stuff.again expensive. lady siam centre near toys r us; alsadd area; is good too.they specialise in thai massages and stuff and their facial is really nice and soothing. had it long time back; but communiacting with them is difficult as they speak only thai and broken english. massage; you can try chinese reflexology massage at ramada; that good too; also the kottakal massage centre in muntaza area; cheap and good for body pains and stuff.both are priced at aprox 100qrs. almost all saloons do facials and some have real extensive range of facials.u need to try out the places to get a feel of it. i just saw your profile; you sound so much like me; except the coke and margarita part.</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C7" RELC_DATE="2006-11-09 22:58:52" RELC_USERID="U25" RELC_USERNAME="welcomeqatar" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>pls let me know where is that massage done? i want to try it.thanks</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C8" RELC_DATE="2006-11-12 13:09:04" RELC_USERID="U18" RELC_USERNAME="gringer" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>thanks ; i guess i wil try the lady shiam; and the bio bil;hhehehe hmmm what else is new to try here in doha?</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C9" RELC_DATE="2006-11-12 16:30:24" RELC_USERID="U22" RELC_USERNAME="Miss Canada" RELC_RELEVANCE2RELQ="PotentiallyUseful">
			<RelCText>Hi Gringer; Ask for Belen at Bio Bil ... she's amazing!! Have fun!! MC</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R10_C10" RELC_DATE="2006-12-08 12:47:13" RELC_USERID="U22" RELC_USERNAME="Miss Canada" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Crawl back to your rock; Troll.</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q1_R22">
		<RelQuestion RELQ_ID="Q1_R22" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2012-01-09 11:28:38" RELQ_USERID="U26" RELQ_USERNAME="Cryptic-writings">
			<RelQSubject>What attracts you more ?</RelQSubject>
			<RelQBody>What attracts you more ?</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q1_R22_C1" RELC_DATE="2012-01-09 11:39:52" RELC_USERID="U27" RELC_USERNAME="drsam" RELC_RELEVANCE2RELQ="Good">
			<RelCText>none: youth</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C2" RELC_DATE="2012-01-09 11:40:08" RELC_USERID="U28" RELC_USERNAME="osamabawab" RELC_RELEVANCE2RELQ="Good">
			<RelCText>massaging stones !</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C3" RELC_DATE="2012-01-09 11:44:25" RELC_USERID="U29" RELC_USERNAME="fea_sad" RELC_RELEVANCE2RELQ="Good">
			<RelCText>believe</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C4" RELC_DATE="2012-01-09 11:46:20" RELC_USERID="U26" RELC_USERNAME="Cryptic-writings" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Girls with short hair cuts .</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C5" RELC_DATE="2012-01-09 12:09:07" RELC_USERID="U30" RELC_USERNAME="Captain_Lost" RELC_RELEVANCE2RELQ="Good">
			<RelCText>NONE - Money</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C6" RELC_DATE="2012-01-09 12:20:06" RELC_USERID="U31" RELC_USERNAME="ishu369" RELC_RELEVANCE2RELQ="Good">
			<RelCText>money of course</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C7" RELC_DATE="2012-01-09 12:26:31" RELC_USERID="U32" RELC_USERNAME="saigon_kids" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Believe</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C8" RELC_DATE="2012-01-09 12:27:34" RELC_USERID="U33" RELC_USERNAME="fictitious_sam" RELC_RELEVANCE2RELQ="Good">
			<RelCText>faith</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C9" RELC_DATE="2012-01-09 12:27:43" RELC_USERID="U34" RELC_USERNAME="cherukkan" RELC_RELEVANCE2RELQ="Good">
			<RelCText>"For me it is ""LOVE"""</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R22_C10" RELC_DATE="2012-01-09 12:32:16" RELC_USERID="U35" RELC_USERNAME="FathimaH" RELC_RELEVANCE2RELQ="Good">
			<RelCText>I always need lots of faith and hope. And agree with captain lost..money is; by a far; very attractive!</RelCText>
		</RelComment>
	</Thread>

	<Thread THREAD_SEQUENCE="Q1_R25">
		<RelQuestion RELQ_ID="Q1_R25" RELQ_CATEGORY="Qatar Living Lounge" RELQ_DATE="2007-12-06 08:45:11" RELQ_USERID="U2" RELQ_USERNAME="anonymous">
			<RelQSubject>You have got to be joking.....Seen in a shop in Downtown Manama !</RelQSubject>
			<RelQBody>[img_assist|nid=54388|title=Placenta cream ????|desc=|link=none|align=left|width=440|height=388] What the hell do you do with Placenta cream ??????</RelQBody>
		</RelQuestion>

		<RelComment RELC_ID="Q1_R25_C1" RELC_DATE="2007-12-06 08:47:35" RELC_USERID="U36" RELC_USERNAME="lima foxtrot" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>No idea!!!!! But looking forward to the answer. lol [img_assist|nid=14395|title=Smile; life is too short!!!!!!!!!!!!!!|desc=|link=none|align=center|width=180|height=97]</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C2" RELC_DATE="2007-12-06 08:50:10" RELC_USERID="U36" RELC_USERNAME="lima foxtrot" RELC_RELEVANCE2RELQ="Good">
			<RelCText>The answer is : RE-BIRTH PLACENTA ANTI-WRINKLE CREAM WITH VITAMIN E &amp; LANOLIN. [img_assist|nid=14395|title=Smile; life is too short!!!!!!!!!!!!!!|desc=|link=none|align=center|width=180|height=97]</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C3" RELC_DATE="2007-12-06 08:50:42" RELC_USERID="U37" RELC_USERNAME="Cornellian" RELC_RELEVANCE2RELQ="Good">
			<RelCText>God bless google :P What is Placenta Serum? Placenta Serum is derived from Bovine Placenta (cow) contains highly biologically active enzymes; proteins; anti-oxidants; amino acids and vitamins to provide the bio-stimulation necessary for the promotion of skin regeneration. If u want to know more: http://www.lifetimehealth.com/sheep_placenta.asp I'm not always right; but I'm never wrong :P - Garfield</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C4" RELC_DATE="2007-12-06 08:53:41" RELC_USERID="U38" RELC_USERNAME="Tigasin321" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>You are the doctor. Does it work? Also please read my pm. Victory attained by violence is tantamount to a defeat; for it is momentary. Mahatma Gandhi</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C5" RELC_DATE="2007-12-06 08:54:13" RELC_USERID="U39" RELC_USERNAME="Spirit2006" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Somehow I can't quite picture having someone smear that on my skin...</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C6" RELC_DATE="2007-12-06 08:55:06" RELC_USERID="U36" RELC_USERNAME="lima foxtrot" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>just seen sheep placenta cream [img_assist|nid=14395|title=Smile; life is too short!!!!!!!!!!!!!!|desc=|link=none|align=center|width=180|height=97]</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C7" RELC_DATE="2007-12-06 08:56:00" RELC_USERID="U38" RELC_USERNAME="Tigasin321" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Does it work? I will ask my friend Bajesus. He will know. Victory attained by violence is tantamount to a defeat; for it is momentary. Mahatma Gandhi</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C8" RELC_DATE="2007-12-06 08:56:34" RELC_USERID="U40" RELC_USERNAME="ChupaRustom" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>Some will go to great length to become beautiful even mud bath in expensive spa</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C9" RELC_DATE="2007-12-06 08:57:45" RELC_USERID="U37" RELC_USERNAME="Cornellian" RELC_RELEVANCE2RELQ="Bad">
			<RelCText>I am completely clueless when it comes to skin care...I'm a shame to women around the world lol; I don't use anything :( But hopefully Scarlett will give me some tips soon! I'm not always right; but I'm never wrong :P - Garfield</RelCText>
		</RelComment>

		<RelComment RELC_ID="Q1_R25_C10" RELC_DATE="2007-12-06 08:59:26" RELC_USERID="U36" RELC_USERNAME="lima foxtrot" RELC_RELEVANCE2RELQ="Good">
			<RelCText>Used for years by only by models and the rich it is now available to everyone that knows where to find this difficult to find product. Sheep Placenta Cream is a product that is used throughout Asia to greatly excelerate the healing process and to reduce the process of scar formation. Sheep Placenta Cream contains pure natural living cell sheep placenta extremely rich in growth and healing nutrition. [img_assist|nid=14395|title=Smile; life is too short!!!!!!!!!!!!!!|desc=|link=none|align=center|width=180|height=97]</RelCText>
		</RelComment>
	</Thread>
</xml>